spring:
  shardingsphere:
    datasource:
      ds:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://127.0.0.1:3306/bbs_1?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF-8
        password: li123456
        username: root
      names: ds
    rules:
      sharding:
        binding-tables:
          - t_order
        broadcast-tables: t_address
        sharding-algorithms:
          t-order-inline:
            type: COMPLEX_INLINE
            props:
              algorithm-expression: t_order_$->{city}_$->{order_id % 2}
              sharding-columns: city,order_id
        tables:
          t_order:
            actual-data-nodes: ds.t_order_$->{['shanghai','beijing']}_$->{0..1}
            table-strategy:
              complex:
                sharding-algorithm-name: t-order-inline
                sharding-columns: city,order_id

    props:
      sql-show: true
