spring:
  application:
    name: oauth2-authorization-server
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/oauth2?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF-8
    password: li123456
    username: root

server:
  port: 9000
  servlet:
    context-path: /uc

mybatis:
  configuration:
    default-fetch-size: 100
    default-statement-timeout: 30
    map-underscore-to-camel-case: true
    use-generated-keys: true
  mapper-locations: classpath*:mappers/**/*-mapper.xml
  type-aliases-package: com.lance.oauth2.server.domain

logging:
  level:
    org.springframework.web: INFO
    org.springframework.security: debug
    org.springframework.security.oauth2: debug
    com.lance.oauth2.server: debug
